Add frontend configuration for blacklist
sulu/SuluCommunityBundle pull request #120
Opened 2019-11-08 12:21 UTC by Prokyonn

| Q | A
| --- | ---
| Bug fix? | no
| New feature? | no
| BC breaks? | no
| Deprecations? | no
| Fixed tickets | fixes #issuenum
| Related issues/PRs | #issuenum
| License | MIT

#### What's in this PR?

Adds the frontend configuration for the blacklist in sulu 2.0.

2019-11-11 09:11 UTC, alexander-schranz commented on Controller/BlacklistItemController.php
> +                    'blacklist',
bc break should be documented in the UPGRADE.md

2019-11-11 09:14 UTC, alexander-schranz requested changes

2019-11-11 09:14 UTC, alexander-schranz commented on SuluCommunityBundle.php
> +                BlacklistItem::class => 'sulu.model.blacklist.class',
Think this should be `blacklist_item.class` or?

and when changing to persistence bundle remove the `sulu_community.blacklisting.item_repository` service definition and use the service create by the Persistence Bundle should be something like `sulu.repository.blacklist_item` or so.

2019-11-11 09:45 UTC, Prokyonn commented on SuluCommunityBundle.php
> +                BlacklistItem::class => 'sulu.model.blacklist.class',
I guess we can then also remove the `sulu_community.blacklisting.user_repository` service definition right ?

2019-11-11 09:50 UTC, alexander-schranz commented on SuluCommunityBundle.php
> +                BlacklistItem::class => 'sulu.model.blacklist.class',
Sure but that Entity seems to be missing here or?

2019-11-11 09:51 UTC, alexander-schranz commented on Controller/BlacklistItemController.php
> +                    'blacklist',
and this should be `blacklistItems` or `blacklist_items` not sure what we use here normally

2019-11-11 09:51 UTC, alexander-schranz commented on Admin/CommunityAdmin.php
> +    const SECURITY_CONTEXT = 'sulu.community.blacklist';
`blacklist_item` to be as specific as possible

2019-11-11 09:53 UTC, alexander-schranz requested changes

2019-11-11 09:53 UTC, alexander-schranz commented on Admin/CommunityAdmin.php
> +    const EDIT_FORM_VIEW = 'sulu_community.blacklist.edit_form';
We should rename this constants to `BLACKLIST_ITEM_...` or we should rename the class to `BlacklistItemAdmin`

2019-11-11 10:29 UTC, Prokyonn commented on SuluCommunityBundle.php
> +                BlacklistItem::class => 'sulu.model.blacklist.class',
yep, I've added it

2019-11-11 12:43 UTC, alexander-schranz requested changes

2019-11-11 12:43 UTC, alexander-schranz commented on UPGRADE.md
> +The name of the relation inside of the `_embedded` field has been changed from `items` to `blacklist_items`.
add empty lune before.

Add also upgrade for repository service ids

2019-11-11 13:06 UTC, alexander-schranz approved these changes

2020-01-13 06:41 UTC, Prokyonn commented
@alexander-schranz ping

2020-04-09 08:09 UTC, alexander-schranz approved these changes

2020-04-09 08:10 UTC, alexander-schranz commented
@Prokyonn needs rebase

2020-04-22 11:18 UTC, alexander-schranz approved these changes

2020-04-22 11:19 UTC, merged